services:
  database:
    container_name: DataBasePetsHeaven
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - pets-data:/var/lib/mysql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  backend:
    container_name: BackEndPetsHeaven
    image: node
    build: 
      context: ./back-end
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - pets-back:/back-end
  frontend:
    container_name: FrontEndPetsHeaven
    image: node
    build: 
      context: ./front-end
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    volumes:
      - pets-front:/front-end
volumes:
  pets-data:
  pets-back:
  pets-front: