services:
  database:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - pets-data:/var/lib/mysql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
volumes:
  pets-data: